# fly.toml app configuration file generated for turso-solitary-forest-4520-autumn-cherry-8457 on 2024-02-12T10:49:46+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'turso-solitary-forest-4520-autumn-cherry-8457'
primary_region = 'arn'

[build]
  dockerfile = 'Dockerfile'
  ignorefile = '.dockerignore'
  build-target = 'run'

[env]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
